name: Python package

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string    # <-- obligatoire
        default: "3.13"

jobs:
  build-and-push-package:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Build package
        working-directory: workers/python
        run: uv build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mon-artifact-python
          path: workers/python/dist/
